name: HidePlayerItems
version: ${project.version}
main: dev.jcsoftware.hideplayeritems.HidePlayerItemsPlugin
author: Jordan Osterberg
api-version: '1.20'
depend: [ProtocolLib]
commands:
  hide:
    description: Change what equipment displays for other players
    usage: /hide none | all | held
    permission: hideplayeritems.hide